spring:
  datasource:
    url: jdbc:mysql://${APP_DB_HOST:localhost}:${APP_DB_PORT:3306}/${APP_DB_SCHEMA:store}?useSSL=false&serverTimezone=UTC&useTimezone=true&useLegacyDatetimeCode=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      test-while-idle: true
      validation-query: 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true